# Generated by Django 5.1.6 on 2025-03-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
